This notebook contains the first task in DELTA. Additionally, the notebook shows how to import the provided data.

### **1. Description of the first Task**

1)      What to submit?

We ask you to submit one zip archive including a Jupyter notebook and a csv file containing your predictions on the test set.

2)      Where to submit?

Submit the zip file via the corresponding Moodle module.

3)      Where to find the data?

The data sets for this task and the demo predictions file 'Demo_Predictions.csv' can be found on the main Moodle page under 'Task 1 Data'. The format of your predictions should be the same as the csv demo file. Also, your predictions should be in the original scale of the train and test datasets. The files 'DELTASS26_train_X.csv' and 'DELTASS26_test_X.csv' contain the predictors in the train and test set, respectviely. The file 'DELTASS26_train_y.csv' contains the target variable in the train set. You can use pandas to import your datasets in the following way: pd.read_csv(file_name,sep=',',header=0,index_col=0).


4)      What is expected?

You are provided with a tabular dataset containing 19 predictor features and 1 target variable. Your task is to build a neural network in keras/tensorflow to predict the continuous target variable. The data is separated into a train set of 1875 data samples, and a test set of 625 data samples.

The jupyter notebook should contain the following elements:

- Preprocessing of your datasets according to the requirements of neural networks. (different features have different descriptive statistics!)
- Implementation of 3 benchmark models: a linear model, a tree-based model and a neural network that has not been tuned. 
- Tuning of a neural network using a hyperparameter optimization library of your choice. The code for hyperparameter tuning should include regularization. 
- A well annotated plot showing the train vs. validation loss of the best performing neural network. 
- Additionally, you should provide an interpretation of why you believe the best performing architecture is suitable for your task in max. 3 sentences.
- A table showing all results (on a validation subset) from the tuned network and your benchmarks.
- Well documented code, which is divided into functions, classes, etc.


5)      How will your submissions be evaluated?

- Pass/fail: based on whether your notebook covers all required components mentioned above and whether your code runs without an error.
- Number of points: determined by the RMSE score of your predictions.

6)      Can I submit after the deadline?
We understand that unexpected circumstances sometimes lead to delayed submissions. While we will accept late submissions via e-mail, please keep in mind that there will be a deduction of 2 points per day for each day the submission is late.

### **2. Data Import**

So that you can import the data with the code cell below, you should put the data in the same folder of the notebook. Otherwise, you would have to adjust the file path.

In [4]:
import pandas as pd

#Predictor features on the train set:
train_X=pd.read_csv('DELTASS26_train_X.csv',sep=',',header=0,index_col=0)
#Target variable on the train set:
train_y=pd.read_csv('DELTASS26_train_y.csv',sep=',',header=0,index_col=0)
#Predictor features on the test set:
test_X=pd.read_csv('DELTASS26_test_X.csv',sep=',',header=0,index_col=0)
#Demo predictions file:
demo_predictions=pd.read_csv('Demo_Predictions.csv',sep=',',header=0,index_col=0)

In [5]:
train_X.head(5)

,0,1,2,3,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
2247,576.862876,118.941013,36.864442,-3844.453211,153.049833,1216.575188,1055.787408,111.237666,27.532591,2.121720,133.213740,499.184594,291.244141,122.809701,326.598858,-357.659748,0.733640,343.128068,7377.299492
816,-519.964665,152.487356,42.803957,8965.090492,175.423991,397.802231,2525.121784,106.036085,595.022787,-253.169013,-2.840755,138.972827,131.423179,134.734812,-3.910438,83.767176,557.159582,694.391959,-69002.946334
2153,-268.637257,201.446002,100.608799,7544.404518,133.975813,354.781676,1583.844900,109.957988,496.738147,-93.226084,15.624221,-69.819507,287.685650,273.224214,30.448455,194.724920,244.074657,366.901671,-41121.428175
1162,221.912111,132.390398,12.575263,-487.048745,136.090808,235.232175,744.472463,114.825842,-83.443809,110.480186,184.106522,1220.268567,230.930712,-9.886667,314.087609,-142.796921,2.428668,86.153047,7047.470827
480,949.533069,141.908066,106.633256,-5722.261554,72.590811,549.951299,686.233202,114.246343,16.245654,111.848648,174.065199,1050.920096,262.491938,-13.923644,196.254658,-41.436895,0.424431,53.277692,6376.903296

In [6]:
train_y.head(5)

               4
2247  909.619133
816  -114.186720
2153 -334.066552
1162  241.265155
480  -125.723772